library(tidyverse)
library(blantyreESBL)
library(here)

# UPDATE 13 Sept 2023 - I've added the musicha and dassim
# Klebs to this plot

# this analysis needs the summarsied card/ariba output file
# data-processed/catb3_card_assembly_stats.csv generated by the script
# scripts/parse_ariba_card_op.R 


catb3_card_df <-
  read_csv(here("SFig2/data-processed/catb3_card_assembly_stats.csv"))

catb3_card_df |>
  mutate(
    ref_start = as.numeric(ref_start),
    ref_end = as.numeric(ref_end)
  ) |>
  select(
    study,
    lane,
    species,
    ref_name,
    ref_len,
    ref_base_assembled,
    pc_ident,
  ) |>
  pivot_longer(-c(study, lane, species, ref_name, ref_len)) |>
  ggplot(aes(fct_reorder(lane, study), value, color = study)) +
  geom_point(size = 1, alpha = 0.8) +
  facet_grid(name ~ species, scale = "free") +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  labs(
    title = "Length/identity of assembled catB3 ARIBA/CARD",
    subtitle = "Length of full catB3 is 633; there are many assemblies at 442b",
    x = "sample"
  )

ggsave(here("ariba-card-catb3-assemblystats.pdf"), width = 8, height = 5)
