#title: "cat lenght/identity"
#author: "JL"
#date: 13/09/23

#load packages
library(tidyverse)
library(blantyreESBL)
library(here)

# UPDATE 13 Sept 2023 - I've added the musicha and dassim
# Klebs to this plot

# this analysis needs the summarised card/ariba output file
# data-processed/catb3_card_assembly_stats.csv generated by the script
# scripts/parse_ariba_card_op.R 


catb3_card_df <-
  read_csv("SFig2/data-processed/catb3_card_assembly_stats.csv")

catb3_card_df |>
  mutate(
    ref_start = as.numeric(ref_start),
    ref_end = as.numeric(ref_end),
  ) |>
  select(
    study,
    lane,
    species,
    ref_name,
    ref_len,
    ref_base_assembled,
    pc_ident,
  ) |>
  pivot_longer(-c(study, lane, species, ref_name, ref_len)) |>
  ggplot(aes(fct_reorder(lane, study), value, color = study)) +
  scale_colour_manual(values = c("#2c7fb8", "red"),
                      name = "Study",
                    labels= c("ESBL", "Bacteraemia")) +
  geom_point(size = 1, alpha = 0.8) +
  facet_grid(name ~ species, scale = "free") +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  theme(strip.background = element_rect(fill = "#f7fcfd")) +
  labs(
    title = "Length/identity of assembled catB3 CARD",
    subtitle = "Length of full catB3 is 633; there are many assemblies at 442b",
    x = "sample"
  ) -> FigS2b

ggsave(here("SF2b_ariba-card-catb3-assemblystats.pdf"), width = 8, height = 5)


### counts
catB3_4_pc_id_counts <- catb3_card_df %>% count(pc_ident, sort = TRUE)
catB4_assembly_counts <- catb3_card_df %>% count(ref_base_assembled, sort = TRUE)
